# Generated by Django 5.2.7 on 2025-10-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('instruction', models.TextField(default='Enter needed informations')),
                ('prompt', models.TextField()),
                ('word_doc', models.FileField(upload_to='templates_files/')),
            ],
        ),
    ]
